name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pandas

      - name: Create Streamlit Cloud app
        uses: streamlit/app@v1
        with:
          # Replace these with your actual Streamlit Cloud app details
          token: ${{ secrets.STREAMLIT_TOKEN }}
          app-name: "movie-recommendation-system"
          app-path: "."
          requirements: "requirements.txt"
